### ISSUE TITLE
Would using atoms as variable bindings cause an issue in memory?

### ISSUE THREAD

**Issue by nthock** [am-kantox/formulae#6]
Hello there,

I am thinking of using this package in my project which allow user to enter the formula on their own. This includes using the user's naming of the variable. Given that the variable bindings is in atom, and atom is not garbage collected, would this cause a memory leak issue?

**Comment by am-kantox** [comment]
It would not cause _memory leak_ per se, but rather a so-called atom DoS attack when the number of atoms exceeds the allowed number (≈1M by default, might be increased via command line options) when the VM crashes.

Generally speaking, generating formulas on the fly based on the user input is not how exactly this library was supposed to be used, but you might consider handling atoms overflow as an expected case (failover after VM crash,) or just restart it on say daily basis.

**Comment by nthock** [comment]
@am-kantox thanks for the prompt reply. I will think of some other ways then. Will close this issue.
