### ISSUE TITLE
(SystemLimitError) a system limit has been reached

### ISSUE THREAD

**Issue by hl** [am-kantox/formulae#9]
When I have the following formulae:

```
timestamp(shift_start_datetime) > timestamp(shift_date(set_datetime(shift_start_datetime, hour: 8, minute: 0), workday)) && timestamp(shift_start_datetime) < timestamp(shift_date(set_datetime(shift_start_datetime, hour: 10, minute: 0), workday))
```

I get the error:

```
(SystemLimitError) a system limit has been reached
    :erlang.binary_to_atom(\"Elixir.Formulae.timestamp(shift_start_datetime) > timestamp(shift_date(set_datetime(shift_start_datetime, hour: 8, minute: 0), workday)) && timestamp(shift_start_datetime) < timestamp(shift_date(set_datetime(shift_start_datetime, hour: 10, minute: 0), workday))\", :utf8)
    (elixir 1.16.2) src/elixir_aliases.erl:138: :elixir_aliases.concat/1
    (formulae 0.15.0) lib/formulae.ex:259: Formulae.ensure_compiled/2
    (formulae 0.15.0) lib/formulae.ex:309: Formulae.compile/2
```

I'm using it in the follow way:

```elixir
  def eval_formula!(input, bindings, opts \\ []) do
    opts = Keyword.put_new(opts, :imports, [__MODULE__])

    with %Formulae{} = formula <- Formulae.compile(input, opts) do
      Formulae.eval!(formula, bindings)
    end
  end
```

**Comment by am-kantox** [comment]
Hi, @hl!

Unfortunately, you’ve met a BEAM [atom limit](https://stackoverflow.com/a/40803125/2035262).

`Formulae` produces a module per new input (unless it saw this input before,) and a module name is an atom, and hence there are drawbacks when one attempts to continiously produce new instances in runtime. The issue has nothing to do with this particular input, it’s a general problem you’ll face when using this library to produce new `Formulae` instances in runtime.

What bugs me, is the error says it treated the input as `Elixir.Formulae.timestamp(...) > timestamp(...) && timestamp(...) < timestamp(...)` (check the first operand,) which is kinda weird once `timestamp/1` has been imported supposedly from `__MODULE__`.


Could you maybe share the `timestamp/1` implementation and `input` please?

**Comment by hl** [comment]
Hi @am-kantox 

I totally forgot to thank you for this amazing library, it saved me hours of work and we are using it in production and it works great.

I'm not sure about the atom limit but then again, I don't know a lot about that.

This is some code that will generate the error on the second input string:

```elixir
defmodule Helper do
  def timestamp(datetime) do
    DateTime.to_unix(datetime)
  end
end

input = "timestamp(start) && timestamp(start)"
formula = Formulae.compile(input, [imports: [Helper]])

Formulae.eval!(formula, [start: DateTime.utc_now()])

input = """
# Some comment to indicate that if this string is too long it will error out
# Some comment to indicate that if this string is too long it will error out
# Some comment to indicate that if this string is too long it will error out
# Some comment to indicate that if this string is too long it will error out

timestamp(start) && timestamp(start)
"""

formula = Formulae.compile(input, [imports: [Helper]])

Formulae.eval!(formula, [start: DateTime.utc_now()])
```

**Comment by am-kantox** [comment]
> thank you for this amazing library

Always welcome.

> some code that will generate the error on the second input string

Argh, gosh, sorry, please disregard my previous comment. This is all about atom length, not about total number of atoms. Please expect kinda fix soon.

Thanks for reporting!

**Comment by am-kantox** [comment]
> Package published to https://hex.pm/packages/formulae/0.16.0
> (e2220728e4b354ccb09c74f08eb21693d85fc8b622da5ffeab627dabccd0d584)
